# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/dock_portfolio.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DockPortfolio(object):
    def setupUi(self, DockPortfolio):
        DockPortfolio.setObjectName("DockPortfolio")
        DockPortfolio.resize(405, 325)
        DockPortfolio.setAutoFillBackground(False)
        DockPortfolio.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        DockPortfolio.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        DockPortfolio.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabla = QtWidgets.QTableView(self.dockWidgetContents)
        self.tabla.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tabla.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla.setAlternatingRowColors(True)
        self.tabla.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tabla.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla.setGridStyle(QtCore.Qt.SolidLine)
        self.tabla.setObjectName("tabla")
        self.tabla.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tabla)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.combo_trades = QtWidgets.QComboBox(self.dockWidgetContents)
        self.combo_trades.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.combo_trades.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.combo_trades.setObjectName("combo_trades")
        self.combo_trades.addItem("")
        self.combo_trades.addItem("")
        self.horizontalLayout.addWidget(self.combo_trades)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        DockPortfolio.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockPortfolio)
        QtCore.QMetaObject.connectSlotsByName(DockPortfolio)

    def retranslateUi(self, DockPortfolio):
        _translate = QtCore.QCoreApplication.translate
        DockPortfolio.setWindowTitle(_translate("DockPortfolio", "Po&rtfolio"))
        self.combo_trades.setItemText(0, _translate("DockPortfolio", "Open"))
        self.combo_trades.setItemText(1, _translate("DockPortfolio", "Closed"))
import iconos_rc
