# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/dock_portfolio.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DockPortfolio(object):
    def setupUi(self, DockPortfolio):
        DockPortfolio.setObjectName("DockPortfolio")
        DockPortfolio.resize(405, 325)
        DockPortfolio.setAutoFillBackground(False)
        DockPortfolio.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        DockPortfolio.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        DockPortfolio.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabla = QtWidgets.QTableView(self.dockWidgetContents)
        self.tabla.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tabla.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla.setAlternatingRowColors(True)
        self.tabla.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tabla.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla.setGridStyle(QtCore.Qt.SolidLine)
        self.tabla.setObjectName("tabla")
        self.tabla.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tabla)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_update = QtWidgets.QPushButton(self.dockWidgetContents)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/actions/update"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_update.setIcon(icon)
        self.btn_update.setObjectName("btn_update")
        self.horizontalLayout.addWidget(self.btn_update)
        self.btn_edit = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btn_edit.setObjectName("btn_edit")
        self.horizontalLayout.addWidget(self.btn_edit)
        self.btn_delete = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout.addWidget(self.btn_delete)
        self.verticalLayout.addLayout(self.horizontalLayout)
        DockPortfolio.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockPortfolio)
        QtCore.QMetaObject.connectSlotsByName(DockPortfolio)

    def retranslateUi(self, DockPortfolio):
        _translate = QtCore.QCoreApplication.translate
        DockPortfolio.setWindowTitle(_translate("DockPortfolio", "Po&rtfolio"))
        self.btn_update.setText(_translate("DockPortfolio", "Update"))
        self.btn_edit.setText(_translate("DockPortfolio", "Edit..."))
        self.btn_delete.setText(_translate("DockPortfolio", "Delete"))
import iconos_rc
