# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/dialog_config.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogConfig(object):
    def setupUi(self, DialogConfig):
        DialogConfig.setObjectName("DialogConfig")
        DialogConfig.setWindowModality(QtCore.Qt.WindowModal)
        DialogConfig.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogConfig.sizePolicy().hasHeightForWidth())
        DialogConfig.setSizePolicy(sizePolicy)
        DialogConfig.setMinimumSize(QtCore.QSize(400, 300))
        DialogConfig.setMaximumSize(QtCore.QSize(400, 300))
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogConfig)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(DialogConfig)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.layoutWidget = QtWidgets.QWidget(self.tab_general)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 361, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.combo_languages = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_languages.sizePolicy().hasHeightForWidth())
        self.combo_languages.setSizePolicy(sizePolicy)
        self.combo_languages.setObjectName("combo_languages")
        self.combo_languages.addItem("")
        self.combo_languages.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.combo_languages)
        self.tabWidget.addTab(self.tab_general, "")
        self.tab_exchanges = QtWidgets.QWidget()
        self.tab_exchanges.setObjectName("tab_exchanges")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_exchanges)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 361, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.check_bittrex = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_bittrex.setObjectName("check_bittrex")
        self.verticalLayout_2.addWidget(self.check_bittrex)
        self.check_bitfinex = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_bitfinex.setObjectName("check_bitfinex")
        self.verticalLayout_2.addWidget(self.check_bitfinex)
        self.check_binance = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_binance.setObjectName("check_binance")
        self.verticalLayout_2.addWidget(self.check_binance)
        self.check_poloniex = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_poloniex.setObjectName("check_poloniex")
        self.verticalLayout_2.addWidget(self.check_poloniex)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_exchanges, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogConfig)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogConfig)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(DialogConfig.accept)
        self.buttonBox.rejected.connect(DialogConfig.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogConfig)

    def retranslateUi(self, DialogConfig):
        _translate = QtCore.QCoreApplication.translate
        DialogConfig.setWindowTitle(_translate("DialogConfig", "Configuracion"))
        self.label.setText(_translate("DialogConfig", "Idioma"))
        self.label_2.setText(_translate("DialogConfig", "TextLabel"))
        self.combo_languages.setItemText(0, _translate("DialogConfig", "es_ES"))
        self.combo_languages.setItemText(1, _translate("DialogConfig", "en_EN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_general), _translate("DialogConfig", "General"))
        self.check_bittrex.setText(_translate("DialogConfig", "Bittrex"))
        self.check_bitfinex.setText(_translate("DialogConfig", "Bitfinex"))
        self.check_binance.setText(_translate("DialogConfig", "Binance"))
        self.check_poloniex.setText(_translate("DialogConfig", "Poloniex"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_exchanges), _translate("DialogConfig", "Exchanges"))
