# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/dialog_alarm.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogAlarm(object):
    def setupUi(self, dialogAlarm):
        dialogAlarm.setObjectName("dialogAlarm")
        dialogAlarm.setWindowModality(QtCore.Qt.NonModal)
        dialogAlarm.resize(294, 312)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialogAlarm.sizePolicy().hasHeightForWidth())
        dialogAlarm.setSizePolicy(sizePolicy)
        dialogAlarm.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(dialogAlarm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(dialogAlarm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.ed_exchange = QtWidgets.QLineEdit(dialogAlarm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ed_exchange.sizePolicy().hasHeightForWidth())
        self.ed_exchange.setSizePolicy(sizePolicy)
        self.ed_exchange.setAlignment(QtCore.Qt.AlignCenter)
        self.ed_exchange.setReadOnly(True)
        self.ed_exchange.setObjectName("ed_exchange")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ed_exchange)
        self.label_2 = QtWidgets.QLabel(dialogAlarm)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.ed_market = QtWidgets.QLineEdit(dialogAlarm)
        self.ed_market.setAlignment(QtCore.Qt.AlignCenter)
        self.ed_market.setReadOnly(True)
        self.ed_market.setObjectName("ed_market")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ed_market)
        self.label_4 = QtWidgets.QLabel(dialogAlarm)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.label_3 = QtWidgets.QLabel(dialogAlarm)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.ed_currentPrice = QtWidgets.QLineEdit(dialogAlarm)
        self.ed_currentPrice.setAlignment(QtCore.Qt.AlignCenter)
        self.ed_currentPrice.setReadOnly(True)
        self.ed_currentPrice.setObjectName("ed_currentPrice")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.ed_currentPrice)
        self.check_autodelete = QtWidgets.QCheckBox(dialogAlarm)
        self.check_autodelete.setObjectName("check_autodelete")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.check_autodelete)
        self.combo_condition = QtWidgets.QComboBox(dialogAlarm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_condition.sizePolicy().hasHeightForWidth())
        self.combo_condition.setSizePolicy(sizePolicy)
        self.combo_condition.setObjectName("combo_condition")
        self.combo_condition.addItem("")
        self.combo_condition.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.combo_condition)
        self.spin_price = QtWidgets.QDoubleSpinBox(dialogAlarm)
        self.spin_price.setDecimals(8)
        self.spin_price.setObjectName("spin_price")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spin_price)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(dialogAlarm)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(dialogAlarm)
        self.buttonBox.accepted.connect(dialogAlarm.accept)
        self.buttonBox.rejected.connect(dialogAlarm.reject)
        QtCore.QMetaObject.connectSlotsByName(dialogAlarm)

    def retranslateUi(self, dialogAlarm):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("dialogAlarm", "Exchange"))
        self.label_2.setText(_translate("dialogAlarm", "Mercado"))
        self.label_4.setText(_translate("dialogAlarm", "Notificar"))
        self.label_3.setText(_translate("dialogAlarm", "Precio actual"))
        self.check_autodelete.setText(_translate("dialogAlarm", "Eliminar automaticamente"))
        self.combo_condition.setItemText(0, _translate("dialogAlarm", "si es menor que"))
        self.combo_condition.setItemText(1, _translate("dialogAlarm", "si es mayor que"))
